## where to install homebrew-cask applications
cask_args appdir: '/Applications'

tap "homebrew/core"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "buo/cask-upgrade"
tap "johanhaleby/kubetail"

brew "azure-cli"
brew "asciinema"
brew "bash-completion"
brew "bat"
brew "fzf"
brew "gh"
brew "git-delta"
brew "git"
brew "github-keygen"
brew "gnupg"
brew "go-task"
brew "go"
brew "hashicorp/tap/terraform"
brew "helm"
brew "htop"
brew "jq"
brew "k9s"
brew "kubectx"
brew "kubetail"
brew "hidetatz/tap/kubecolor"
brew "mas"
brew "most"
brew "neovim"
brew "nmap"
brew "pass"
brew "python@3.11", link: false
brew "shellcheck"
brew "shfmt"
brew "skopeo"
brew "stern"
brew "tree"
brew "wget"
brew "yq"
cask "docker"
cask "hashicorp-vagrant"
cask "google-chrome"
cask "postman"
cask "visual-studio-code"

